name: Build & deploy React app to Azure Web App (gothamblog)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install & build
        run: |
          cd frontend
          npm ci
          npm run build

      # Zip only the production build
      - name: Package build output
        run: |
          cd frontend/dist
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp-package
          path: frontend/release.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write     # for OIDC (optional)
      contents: read      # for checkout

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp-package

      - name: Unzip package
        run: unzip release.zip -d package

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id:     ${{ secrets.AZUREAPPSERVICE_CLIENTID_1D14A1BEA9D2482F90EE1BFB757E876A }}
          tenant-id:     ${{ secrets.AZUREAPPSERVICE_TENANTID_275D1527072E4844945D8E57C73EFC88 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C7F1D6929C804CA490D122F36B0A305E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'gothamblog'
          slot-name: 'Production'
          package: './package'
